### ISSUE TITLE
[Feature] Add gotests templates arguments to configuration

### ISSUE THREAD

**Issue by elliottminns** [olexsmir/gopher.nvim#27]
gotests provides a number of templates in order to have different testing setup boilerplate. With one of these popular ones being testify.

It would be awesome to be able to configure this in the nvim setup function so that we're able to change the template in our configuration.

I'd love to discuss approaches for this, it could be as simple as adding another table to the setup opts for `args` but wondering if that is the best approach long term.

**Comment by olexsmir** [comment]
Thank you for the idea, I didn't even realize that `gotests` has this feature.

I'll implement this(and others) feature ASAP. 
Currently, I'm busy because I'm finishing high school and preparing for exams :sweat_smile:

**Comment by elliottminns** [comment]
I'm very happy to lend a hand here as well, especially if you're busy.

I'm curious to know what you think would be a good idea for the configuration design. Perhaps extending the setup functions opts like the below?

```lua
require("gopher").setup {
  commands = {
     ...
  }
  opts = {
    gotests = {
       template = "testify",
     }
  }
}
```

**Comment by olexsmir** [comment]
I think that it might be without an `opts` table, just put `gotests`/etc on the root level.

Something like this:
```lua
require("gopher").setup {
  commands = { ... },
  gotests = {
    template = "testify",
  },
  ...
}
```

To me it's looking more cleaner
