### ISSUE TITLE
GoTagAdd json struct not found

### ISSUE THREAD

**Issue by Gpihuier** [olexsmir/gopher.nvim#30]
### I wonder if my posture is wrong

```go
type User struct {
  Username string
  Nickname string
}
```

### finally, thanks for this project because it is very useful

**Comment by olexsmir** [comment]
Where do you set your cursor, you need to be at a struct declaration line for this to work. Currently, you must set course on the declaration line, in near feature it will be fixed

**Comment by Gpihuier** [comment]
my cursor in on the struct .  still experiencing that kind of problem 
thank you very much for answering my question
