### ISSUE TITLE
`GoTagAdd json`: struct not found

### ISSUE THREAD

**Issue by garrefa** [olexsmir/gopher.nvim#41]
Hi guys. 

I have the same as issue #30

Doesn't matter where I place the cursor, when I type `: GoTagAdd json` it says struct not found.

Any idea what can go wrong?

Thanks

```golang
package main

import (
	"errors"
	"fmt"
)

type User struct {
  Email string
  Name string
  Age uint
}

func NewUser(name string, email string, age uint) (User, error) {
  if age < 13 || age > 120 { return User{}, errors.New("Invalid user age") }
  if name == "" { return User{}, errors.New("Name cannot be empty")}
  return User{
    Name: name,
    Age: age,
    Email: email,
  }, nil
}

func main() {
  user, _ := NewUser("Alex", "alex@gmail.com", 41)
  fmt.Println(user.Name)
}

```

**Comment by olexsmir** [comment]
check if you have `go` tree-sitter parser installed. and you have to place your cursor somewhere struct declaration.

P.S: i have checked this code snippet and it worked for me

**Comment by nosilex** [comment]
Thanks @olexsmir, I was missing `:TSInstall go`.
