### ISSUE TITLE
Error in GoTestAdd

### ISSUE THREAD

**Issue by bwafi** [olexsmir/gopher.nvim#53]
![image](https://github.com/olexsmir/gopher.nvim/assets/112289694/77cfcbff-bf6c-4075-94bc-24e0d1cd66dd)

**Comment by olexsmir** [comment]
it looks like you haven't installed `gotests` tool, run `:GoInstallDeps` to install the missing deps

**Comment by kirylvarykau** [comment]
Hey, I've got the same issue :( 
<img width="2366" alt="image" src="https://github.com/olexsmir/gopher.nvim/assets/35407446/4e6e7258-575e-44b2-a4b5-e2f4596832cf">

I have dependencies installed :( 
<img width="500" alt="image" src="https://github.com/olexsmir/gopher.nvim/assets/35407446/199c37fe-4946-4a36-8e7f-b9a2fdf54e79">

What else it could be? Thank you in advance

**Comment by olexsmir** [comment]
check if `$GOPATH/bin` in your $PATH?

**Comment by kirylvarykau** [comment]
Hi!

I think so, I have this output (see below) 
 
Adding `GoTagAdd` works without any issues. Same as `goiferr` :( 

Anything else I could try? Thank you 

Output of $PATH:
`
/usr/local/go/bin
/Users/kirylvarykau/go/bin

`
