### ISSUE TITLE
gomodifytags: executable not found

### ISSUE THREAD

**Issue by sai-sy** [olexsmir/gopher.nvim#62]
I can't figure out what I've installed wrong here. I've ran :GoInstallDeps and I followed the rest of the tutorial to a tee. What am I missing.

I'm using nvchad and my full config is up on a repo

```bash
go install github.com/fatih/gomodifytags@latest
```
##### `plugins.lua`
```lua
  {
    "olexsmir/gopher.nvim",
    ft = "go",
    config = function(_, opts)
      require("gopher").setup(opts)
      require("core.utils").load_mappings("gopher")
    end,
    build = function()
      vim.cmd [[silent! GoInstallDeps]]
    end,
  },

```

**Comment by olexsmir** [comment]
Hello, sorry for the long wait. Mainly this problem appears when `$GOPATH/bin` is not in `$PATH`. Check if you can execute the `gomodifytags` in the shell

**Comment by sai-sy** [comment]
No worries, it does not execute but running :GoInstallDeps gives me `Not an editor command:`

**Comment by olexsmir** [comment]
It might happen because the plugin is not loaded, as I see you load it only on Go files.

**Comment by sai-sy** [comment]
I'm working and trying everything from a Go project. I also have my full config on my nvim repo

**Comment by V1con** [comment]
Had the same issue, but adding the go binaries to $PATH fixed it.

basically check in terminal `echo $GOPATH`. If its empty, go defaults to /home/<user>/go/ as path.
After confirming that this is the correct directory go uses this folder, you just need to add in you ~/.bashrc file this line: `export PATH="$PATH:/home/<user>/go/bin"`

**Comment by sai-sy** [comment]
THIS WORKED. thank you. I thought I had to go binaries in the PATH and didn't think
