### ISSUE TITLE
Error "struct not found" on using :GoTagAdd json

### ISSUE THREAD

**Issue by koul1sh** [olexsmir/gopher.nvim#73]
After saving the file, running :GoTagAdd  says "struct not found".
![Screenshot 2024-09-25 234921](https://github.com/user-attachments/assets/a942cad6-94df-47e1-be98-eddb3b2baaf6)

**Comment by olexsmir** [comment]
Hey :wave: 

I tried to reproduce it using the latest version of the plugin and its dependencies, but I couldn't do it.

Can you please provide:
1. more information about your setup,
1. give the code snippet on which it doesn't work,
1. and results of `:checkhealth gopher`

**Comment by vansh845** [comment]
worked with :GoInstallDeps , thanks!!
